import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import fastifyStatic from '@fastify/static';
import { DatabaseSync } from 'node:sqlite';
import jwt from 'jsonwebtoken';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = path.join(root, 'data');
const uploadDir = path.join(dataDir, 'uploads');
const adminDir = path.join(root, 'public', 'admin');
fs.mkdirSync(uploadDir, { recursive: true });
const host = process.env.SUCHAT_HOST || '127.0.0.1';
const port = Number(process.env.SUCHAT_PORT || 8787);
const secret = process.env.SUCHAT_JWT_SECRET || 'suchat-local-development-secret';
const adminHandle = process.env.SUCHAT_ADMIN_HANDLE || 'admin';
const adminPassword = process.env.SUCHAT_ADMIN_PASSWORD || 'change-me';
const db = new DatabaseSync(path.join(dataDir, 'suchat.db'));
db.exec('PRAGMA journal_mode = WAL');
db.exec("CREATE TABLE IF NOT EXISTS admins (id TEXT PRIMARY KEY, handle TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, handle TEXT UNIQUE NOT NULL, display_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, last_seen_at TEXT); CREATE TABLE IF NOT EXISTS settings (user_id TEXT PRIMARY KEY, glass_mode TEXT NOT NULL DEFAULT 'liquid_glass', performance_profile TEXT NOT NULL DEFAULT 'full', page_transition TEXT NOT NULL DEFAULT 'shared_element', theme_mode TEXT NOT NULL DEFAULT 'system', reduced_motion INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, level TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL);");
const now = () => new Date().toISOString();
const makeId = (prefix) => prefix + '_' + crypto.randomUUID();
if (!db.prepare('SELECT id FROM admins WHERE handle = ?').get(adminHandle)) db.prepare('INSERT INTO admins (id,handle,password,role,created_at) VALUES (?,?,?,?,?)').run(makeId('adm'), adminHandle, adminPassword, 'owner', now());
const app = Fastify({ logger: false });
await app.register(cookie);
await app.register(fastifyStatic, { root: adminDir, prefix: '/admin/' });
app.addHook('onRequest', async (request, reply) => { reply.header('Access-Control-Allow-Origin', request.headers.origin || '*'); reply.header('Access-Control-Allow-Credentials', 'true'); reply.header('Access-Control-Allow-Headers', 'Content-Type, Authorization'); });
app.options('*', async (_, reply) => reply.code(204).send());
const userSession = (request) => { const token = request.headers.authorization?.replace(/^Bearer /, ''); if (!token) return null; try { return jwt.verify(token, secret); } catch { return null; } };
const adminGuard = async (request, reply) => { const token = request.cookies.suchat_admin_session || request.headers.authorization?.replace(/^Bearer /, ''); try { request.admin = jwt.verify(token, secret); } catch { return reply.code(401).send({ error: 'admin_auth_required' }); } };
app.get('/api/v1/health', async () => ({ status: 'ok', service: 'suchat-server-local', version: '0.1.0', time: now(), database: 'ready' }));
app.get('/api/v1/meta', async () => ({ name: 'Suchat Local Server', apiVersion: 'v1', websocketUrl: 'ws://' + host + ':' + port + '/ws', features: { moments: true, driftBottles: true, localUpload: true, adminWeb: true } }));
app.post('/api/v1/auth/register', async (request, reply) => { const body = request.body || {}; const handle = body.handle; const displayName = body.displayName; const password = body.password; if (!handle || !displayName || !password) return reply.code(400).send({ error: 'handle_displayName_password_required' }); if (db.prepare('SELECT id FROM users WHERE handle = ?').get(handle)) return reply.code(409).send({ error: 'handle_taken' }); const id = makeId('usr'); db.prepare('INSERT INTO users (id,handle,display_name,status,created_at,last_seen_at) VALUES (?,?,?,?,?,?)').run(id, handle, displayName, 'active', now(), now()); db.prepare('INSERT INTO settings (user_id) VALUES (?)').run(id); const accessToken = jwt.sign({ sub: id, kind: 'user' }, secret, { expiresIn: '7d' }); return { user: { id, handle, displayName }, tokens: { accessToken } }; });
app.get('/api/v1/me', async (request, reply) => { const session = userSession(request); if (!session) return reply.code(401).send({ error: 'auth_required' }); const user = db.prepare('SELECT id,handle,display_name AS displayName,status,created_at AS createdAt,last_seen_at AS lastSeenAt FROM users WHERE id = ?').get(session.sub); return user || reply.code(404).send({ error: 'user_not_found' }); });
app.get('/api/v1/me/appearance', async (request, reply) => { const session = userSession(request); if (!session) return reply.code(401).send({ error: 'auth_required' }); const s = db.prepare('SELECT glass_mode,performance_profile,page_transition,theme_mode,reduced_motion FROM settings WHERE user_id = ?').get(session.sub); return { glassMode: s.glass_mode, performanceProfile: s.performance_profile, pageTransition: s.page_transition, themeMode: s.theme_mode, reducedMotion: Boolean(s.reduced_motion) }; });
app.put('/api/v1/me/appearance', async (request, reply) => { const session = userSession(request); if (!session) return reply.code(401).send({ error: 'auth_required' }); const b = request.body || {}; const glassMode = b.glassMode || 'liquid_glass'; const performanceProfile = b.performanceProfile || 'full'; const pageTransition = b.pageTransition || 'shared_element'; if (!['liquid_glass','blur','none'].includes(glassMode) || !['full','balanced','reduced','off'].includes(performanceProfile) || !['shared_element','miuix','aosp','reduced_motion'].includes(pageTransition)) return reply.code(400).send({ error: 'invalid_appearance_value' }); db.prepare('UPDATE settings SET glass_mode=?,performance_profile=?,page_transition=?,theme_mode=?,reduced_motion=? WHERE user_id=?').run(glassMode, performanceProfile, pageTransition, b.themeMode || 'system', b.reducedMotion ? 1 : 0, session.sub); return { glassMode, performanceProfile, pageTransition, themeMode: b.themeMode || 'system', reducedMotion: Boolean(b.reducedMotion) }; });
app.post('/api/admin/v1/auth/login', async (request, reply) => { const b = request.body || {}; const admin = db.prepare('SELECT id,handle,role FROM admins WHERE handle=? AND password=?').get(b.handle, b.password); if (!admin) return reply.code(401).send({ error: 'invalid_credentials' }); const token = jwt.sign({ sub: admin.id, handle: admin.handle, role: admin.role, kind: 'admin' }, secret, { expiresIn: '8h' }); reply.setCookie('suchat_admin_session', token, { httpOnly: true, sameSite: 'lax', path: '/' }); return { admin }; });
app.get('/api/admin/v1/me', { preHandler: adminGuard }, async (request) => ({ id: request.admin.sub, handle: request.admin.handle, role: request.admin.role }));
app.get('/api/admin/v1/dashboard', { preHandler: adminGuard }, async () => { const databaseFile = path.join(dataDir, 'suchat.db'); return { users: { total: db.prepare('SELECT COUNT(*) AS total FROM users').get().total }, realtime: { connections: 0, onlineUsers: 0 }, content: { messagesToday: 0, momentsToday: 0, driftingBottles: 0, openReports: 0 }, storage: { databaseBytes: fs.statSync(databaseFile).size, uploadsBytes: 0 } }; });
app.get('/api/admin/v1/users', { preHandler: adminGuard }, async (request) => { const q = '%' + (request.query.q || '') + '%'; return { items: db.prepare('SELECT id,handle,display_name AS displayName,status,created_at AS createdAt,last_seen_at AS lastSeenAt FROM users WHERE handle LIKE ? OR display_name LIKE ? ORDER BY created_at DESC LIMIT 100').all(q, q) }; });
app.get('/api/admin/v1/system/status', { preHandler: adminGuard }, async () => ({ server: { startedAt, uptimeSeconds: Math.round((Date.now() - startedMs) / 1000), version: '0.1.0' }, database: { path: 'data/suchat.db', sizeBytes: fs.statSync(path.join(dataDir, 'suchat.db')).size, integrity: 'ok' }, storage: { uploadsPath: 'data/uploads', sizeBytes: 0 }, realtime: { connections: 0 } }));
app.get('/admin', async (_, reply) => reply.sendFile('index.html'));
const startedAt = now();
const startedMs = Date.now();
app.listen({ host, port }).then(() => console.log('Suchat Local Server ready: http://' + host + ':' + port));
